import { Product, Category, Recipe } from './types';

export const categories: Category[] = [
  {
    id: 'all',
    name: 'All Items',
    iconName: 'LayoutGrid',
    description: 'Explore our entire collection of fresh groceries',
    color: 'from-slate-500 to-slate-600',
  },
  {
    id: 'biscuits-cookies',
    name: 'Biscuits & Cookies',
    iconName: 'Cookie',
    description: 'Crispy, sweet, and premium cookies & cream biscuits',
    color: 'from-amber-500 to-amber-600',
  },
  {
    id: 'snacks-instant',
    name: 'Snacks & Instant Foods',
    iconName: 'Flame',
    description: 'Quick 2-minute noodles, spicy snacks, and namkeen',
    color: 'from-red-500 to-red-600',
  },
  {
    id: 'papads-savouries',
    name: 'Papads & Savouries',
    iconName: 'Disc',
    description: 'Traditional crunchy potato, sabudana, and urad papads',
    color: 'from-orange-500 to-orange-600',
  },
  {
    id: 'staples-essentials',
    name: 'Staples & Spices',
    iconName: 'Wheat',
    description: 'High-quality pulses (dals), pure sugar, salts, and whole cloves',
    color: 'from-yellow-500 to-yellow-600',
  },
  {
    id: 'oils-ghee',
    name: 'Cooking Oils & Ghee',
    iconName: 'Droplet',
    description: 'Pure mustard oil, soyabean oil, and rich cow desi ghee',
    color: 'from-amber-600 to-yellow-700',
  },
  {
    id: 'household-care',
    name: 'Household & Cleaning',
    iconName: 'Sparkles',
    description: 'Premium washing powders, soap bars, and personal care',
    color: 'from-blue-500 to-blue-600',
  },
];

export const products: Product[] = [
  // --- BISCUITS & COOKIES ---
  {
    id: 'good-day-cashew',
    name: 'Britannia Good Day Cashew Cookies',
    brand: 'Britannia',
    category: 'biscuits-cookies',
    price: 10,
    mrp: 12,
    unit: '75g',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/good-day-cashew.jpeg',
    description: 'Rich, buttery cookies loaded with premium cashew nuts. Perfect for your morning or evening tea time.',
    isVeg: true,
    specialOffer: 'Special Price Rs. 10',
    colorTheme: 'amber',
    rating: 4.8,
    reviewsCount: 320,
    inStock: true,
  },
  {
    id: 'oreo-choco',
    name: 'Cadbury Oreo Choco Crème Sandwich',
    brand: 'Cadbury',
    category: 'biscuits-cookies',
    price: 10,
    mrp: 15,
    unit: '120g',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/oreo-choco.jpeg',
    description: 'Delicious chocolatey sandwich cookies stuffed with sweet rich chocolate crème. Best with cold milk!',
    isVeg: true,
    specialOffer: 'Special Price Rs. 10',
    colorTheme: 'blue',
    rating: 4.9,
    reviewsCount: 412,
    inStock: true,
  },
  {
    id: 'bounce-choco',
    name: 'Sunfeast Bounce Choco Crème Biscuits',
    brand: 'Sunfeast',
    category: 'biscuits-cookies',
    price: 10,
    mrp: 12,
    unit: '70g',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/bounce.jpeg',
    description: 'Crispy chocolate biscuits with delicious chocolate liquid crème core. Soft crunch in every single bite.',
    isVeg: true,
    specialOffer: 'Special Price Rs. 10',
    colorTheme: 'yellow',
    rating: 4.5,
    reviewsCount: 198,
    inStock: true,
  },
  {
    id: 'parle-g',
    name: 'Parle-G Original Gluco Biscuits',
    brand: 'Parle',
    category: 'biscuits-cookies',
    price: 10,
    mrp: 12,
    unit: '110g',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/parle-g.jpeg',
    description: 'India\'s favourite gluco biscuits. Rich in wheat energy and milk nutrients, an iconic companion for hot tea.',
    isVeg: true,
    specialOffer: 'Special Price Rs. 10',
    colorTheme: 'green',
    rating: 4.9,
    reviewsCount: 856,
    inStock: true,
  },
  {
    id: 'desi-chawal',
    name: 'Desi Chawal',
    brand: 'Desi',
    category: 'staples-essentials',
    price: 40,
    mrp: 50,
    unit: '1 Kg',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/chawal.jpeg',
    description: 'Traditional Indian premium rice (Chawal). Cleaned and packed in a hygienic facility, perfect for daily meals.',
    isVeg: true,
    specialOffer: 'Special Offer - Rs. 40',
    colorTheme: 'amber',
    rating: 4.6,
    reviewsCount: 142,
    inStock: true,
  },
  {
    id: 'moms-magic-butter',
    name: 'Sunfeast Mom\'s Magic Butter Cookies',
    brand: 'Sunfeast',
    category: 'biscuits-cookies',
    price: 10,
    mrp: 12,
    unit: '75g',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/moms-magic-butter.jpeg',
    description: 'Crisp cookies prepared with high-quality cow butter and milk. Made with a touch of mother\'s love.',
    isVeg: true,
    specialOffer: 'Special Price Rs. 10',
    colorTheme: 'red',
    rating: 4.7,
    reviewsCount: 260,
    inStock: true,
  },
  {
    id: 'unibic-cashew-almond',
    name: 'Unibic Cashew Almond Biscuits',
    brand: 'Unibic',
    category: 'biscuits-cookies',
    price: 10,
    mrp: 15,
    unit: '90g',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/cashew.jpeg',
    description: 'Premium nuts cookies packed with the double richness of crunchy almonds and delicious cashews.',
    isVeg: true,
    specialOffer: '20% EXTRA Volume',
    colorTheme: 'yellow',
    rating: 4.6,
    reviewsCount: 185,
    inStock: true,
  },
  {
    id: 'patanjali-doodh',
    name: 'Patanjali Doodh Biscuits 100% Atta',
    brand: 'Patanjali',
    category: 'biscuits-cookies',
    price: 10,
    mrp: 12,
    unit: '100g',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/patanjali-doodh.jpeg',
    description: '100% whole wheat atta biscuits with cow milk nutrition. Zero cholesterol and zero trans fat.',
    isVeg: true,
    specialOffer: '100% Atta Health',
    colorTheme: 'cyan',
    rating: 4.5,
    reviewsCount: 130,
    inStock: true,
  },
  {
    id: 'britannia-bourbon',
    name: 'Britannia Bourbon The Original',
    brand: 'Britannia',
    category: 'biscuits-cookies',
    price: 10,
    mrp: 15,
    unit: '120g',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/britannia-bourbon.jpeg',
    description: 'Classic chocolate cream sandwich biscuits sprinkled with sugar crystals. Ideal treat for chocolate lovers.',
    isVeg: true,
    specialOffer: 'Special Price Rs. 10',
    colorTheme: 'purple',
    rating: 4.8,
    reviewsCount: 295,
    inStock: true,
  },
  {
    id: 'patanjali-butter-cookies',
    name: 'Patanjali Premium Atta Butter Cookies',
    brand: 'Patanjali',
    category: 'biscuits-cookies',
    price: 10,
    mrp: 15,
    unit: '100g',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/patanjali-butter-cookies.jpeg',
    description: 'Made from pure cow milk butter and premium wheat flour. Free from artificial colors and harmful chemical preservatives.',
    isVeg: true,
    specialOffer: 'Cow Butter - Rs. 10',
    colorTheme: 'sky',
    rating: 4.6,
    reviewsCount: 112,
    inStock: true,
  },
  {
    id: 'dark-fantasy-fills',
    name: 'Sunfeast Dark Fantasy Choco Fills',
    brand: 'Sunfeast',
    category: 'biscuits-cookies',
    price: 10,
    mrp: 15,
    unit: '75g',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/dark-fantasy-fills.jpeg',
    description: 'Perfect dark baked cookie crust with a premium molten chocolate cream core. Warm it up for 10 seconds for a heavenly experience.',
    isVeg: true,
    specialOffer: 'Premium Pack Rs. 10',
    colorTheme: 'slate',
    rating: 4.9,
    reviewsCount: 520,
    inStock: true,
  },

  // --- SNACKS & INSTANT FOODS ---
  {
    id: 'maggi-noodles',
    name: 'Maggi 2-Minute Masala Noodles',
    brand: 'Nestle',
    category: 'snacks-instant',
    price: 14,
    mrp: 14,
    unit: '70g',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/maggi-noodles.jpeg',
    description: 'The taste of childhood! Instant wheat noodles packed with the signature 12-spice tastemaker sachet.',
    isVeg: true,
    specialOffer: 'Truly Good Spices',
    colorTheme: 'yellow',
    rating: 4.9,
    reviewsCount: 940,
    inStock: true,
  },
  {
    id: 'yippee-noodles-4pack',
    name: 'Sunfeast Yippee Noodles Magic Masala (4-in-1)',
    brand: 'Sunfeast',
    category: 'snacks-instant',
    price: 48,
    mrp: 52,
    unit: '280g (4 Pack)',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/yippee-noodles-4pack.jpeg',
    description: 'Long, non-sticky and round noodles that do not lump. Enriched with real vegetable garnishing and hot spices.',
    isVeg: true,
    specialOffer: 'Save Rs. 4',
    colorTheme: 'orange',
    rating: 4.7,
    reviewsCount: 310,
    inStock: true,
  },
  {
    id: 'yippee-noodles-single',
    name: 'Sunfeast Yippee Noodles Magic Masala',
    brand: 'Sunfeast',
    category: 'snacks-instant',
    price: 12,
    mrp: 14,
    unit: '70g',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/yippee-noodles-single.jpeg',
    description: 'Single instant block of delicious non-sticky masala noodles. Keeps you filled and satisfied.',
    isVeg: true,
    specialOffer: 'Magic Masala Pack',
    colorTheme: 'red',
    rating: 4.6,
    reviewsCount: 225,
    inStock: true,
  },
  {
    id: 'haldiram-khatta-meetha',
    name: 'Haldiram\'s Khatta Meetha Savoury Mix',
    brand: 'Haldiram\'s',
    category: 'snacks-instant',
    price: 10,
    mrp: 10,
    unit: '80g',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/haldiram-khatta-meetha.jpeg',
    description: 'A blend of salty and sweet fried pulses, cornflakes, thick sev, and premium raisins. Perfect teatime snack.',
    isVeg: true,
    specialOffer: 'Savoury Treat',
    colorTheme: 'red',
    rating: 4.7,
    reviewsCount: 480,
    inStock: true,
  },
  {
    id: 'haldiram-peanuts',
    name: 'Haldiram\'s Classic Salted Peanuts',
    brand: 'Haldiram\'s',
    category: 'snacks-instant',
    price: 10,
    mrp: 10,
    unit: '40g',
    description: 'Perfectly roasted, crunchy double-peeled peanuts sprinkled with premium edible iodized salt.',
    isVeg: true,
    specialOffer: 'Source of Protein',
    colorTheme: 'pink',
    rating: 4.5,
    reviewsCount: 154,
    inStock: true,
  },
  {
    id: 'haldiram-nut-cracker',
    name: 'Haldiram\'s Classic Nut Cracker Namkeen',
    brand: 'Haldiram\'s',
    category: 'snacks-instant',
    price: 10,
    mrp: 10,
    unit: '40g',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/haldiram-nut-cracker.jpeg',
    description: 'Premium raw whole peanuts covered in spicy, crispy gram flour batter and deep fried. Truly mouthwatering.',
    isVeg: true,
    specialOffer: 'Crispy & Crunchy',
    colorTheme: 'indigo',
    rating: 4.8,
    reviewsCount: 289,
    inStock: true,
  },
  {
    id: 'kurkure-masala',
    name: 'Kurkure Masala Munch Crisp',
    brand: 'Kurkure',
    category: 'snacks-instant',
    price: 10,
    mrp: 10,
    unit: '50g',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/kings-soyabean-oil.jpeg',
    description: 'Crispy, crooked-shaped corn puffs heavily seasoned with standard Indian spices. Chatpata & crunchy!',
    isVeg: true,
    specialOffer: 'Now Tastier!',
    colorTheme: 'orange',
    rating: 4.7,
    reviewsCount: 610,
    inStock: true,
  },
  {
    id: 'bingo-tedhe-medhe',
    name: 'Bingo! Tedhe Medhe Masala Tadka',
    brand: 'Bingo!',
    category: 'snacks-instant',
    price: 10,
    mrp: 10,
    unit: '45g',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/bingo-tedhe-medhe.jpeg',
    description: 'Spicy snack sticks crafted with a mix of pulses, rice, and corn. Coated with an authentic hot Indian masala tadka.',
    isVeg: true,
    specialOffer: 'Special Rs. 10 Price',
    colorTheme: 'pink',
    rating: 4.6,
    reviewsCount: 345,
    inStock: true,
  },

  // --- PAPADS & SAVOURIES ---
  {
    id: 'zhakaas-rice-papad',
    name: 'Zhakaas Red Chilly Rice Papad',
    brand: 'Zhakaas',
    category: 'papads-savouries',
    price: 18,
    mrp: 20,
    unit: '100g',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/zhakaas.jpeg',
    description: 'Hygienically prepared rice flour disc with hot red chilly seasoning. Gluten-free with no trans fats.',
    isVeg: true,
    specialOffer: '10% OFF Value Pack',
    colorTheme: 'sky',
    rating: 4.4,
    reviewsCount: 96,
    inStock: true,
  },
  {
    id: 'mothers-sabudana-papad',
    name: 'Sendha Namak',
    brand: 'Mother\'s Recipe',
    category: 'papads-savouries',
    price: 35,
    mrp: 40,
    unit: '100g',
    description: 'Tapioca pearl crispies made with premium sendha namak (rock salt). Ideal and allowed for fasting (vrat).',
    isVeg: true,
    specialOffer: 'Best for Fasting',
    colorTheme: 'red',
    rating: 4.8,
    reviewsCount: 167,
    inStock: true,
  },
  {
    id: 'rozana-urad-papad',
    name: 'Rozana Udad Punjabi Masala Papad',
    brand: 'Rozana',
    category: 'papads-savouries',
    price: 38,
    mrp: 45,
    unit: '200g',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/urad.jpeg',
    description: '100% natural urad dal flour disc hand-rolled in Bikaner. Prepared using pure RO water and loaded with black pepper.',
    isVeg: true,
    specialOffer: 'Authentic Bikaner Taste',
    colorTheme: 'emerald',
    rating: 4.7,
    reviewsCount: 204,
    inStock: true,
  },
  {
    id: 'mothers-potato-papad',
    name: 'Mother\'s Recipe Potato (Aloo) Papad',
    brand: 'Mother\'s Recipe',
    category: 'papads-savouries',
    price: 30,
    mrp: 35,
    unit: '100g',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/mothers-potato-papad.jpeg',
    description: 'Sun-dried potato discs with subtle salt and spice. Deep fry or roast over a direct flame for an amazing crisp.',
    isVeg: true,
    specialOffer: 'Fresh & Crispy',
    colorTheme: 'amber',
    rating: 4.5,
    reviewsCount: 110,
    inStock: true,
  },

  // --- STAPLES & ESSENTIALS ---
  {
    id: 'pure-sugar',
    name: 'Premium Sulphur-Free White Sugar',
    brand: 'Ghar Se',
    category: 'staples-essentials',
    price: 44,
    mrp: 50,
    unit: '1 Kg',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/pure-sugar.jpeg',
    description: 'Sulphur-free, sparkling white medium-grade sugar crystals. Dissolves quickly and sweetens completely.',
    isVeg: true,
    specialOffer: 'Pure Refined',
    colorTheme: 'red',
    rating: 4.8,
    reviewsCount: 389,
    inStock: true,
  },
  {
    id: 'kings-mishri',
    name: 'King\'s Pure Mishri (Candy Sugar)',
    brand: 'King\'s',
    category: 'staples-essentials',
    price: 28,
    mrp: 35,
    unit: '200g',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/kings-mishri.jpeg',
    description: 'Pure, crystalline unrefined candy sugar. Widely used as mouth freshener after meals with fennel seeds (saunf).',
    isVeg: true,
    specialOffer: 'Hygienic Pack',
    colorTheme: 'slate',
    rating: 4.6,
    reviewsCount: 94,
    inStock: true,
  },
  {
    id: 'tata-salt',
    name: 'Tata Salt Vacuum Evaporated Iodised Salt',
    brand: 'Tata',
    category: 'staples-essentials',
    price: 24,
    mrp: 28,
    unit: '1 Kg',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/WhatsApp%20Image%202026-07-03%20at%2013.59.32.jpeg',
    description: 'Desh Ka Namak! Vacuum evaporated iodized salt ensures consistent salty taste and healthy iodine development.',
    isVeg: true,
    specialOffer: 'Balanced Taste',
    colorTheme: 'orange',
    rating: 4.9,
    reviewsCount: 1040,
    inStock: true,
  },
  {
    id: 'catch-black-salt',
    name: 'Catch Sprinkler Iodised Black Salt',
    brand: 'Catch',
    category: 'staples-essentials',
    price: 18,
    mrp: 20,
    unit: '100g',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/catch-black-salt.jpeg',
    description: 'Tangy and volcanic black salt (Kala Namak) in an easy-to-shake sprinkler bottle. Great for salads, curd, and fruits.',
    isVeg: true,
    specialOffer: 'Easy Sprinkler',
    colorTheme: 'pink',
    rating: 4.7,
    reviewsCount: 220,
    inStock: true,
  },
  {
    id: 'soya-chunks',
    name: 'Swadeshi High Protein Soya Chunks',
    brand: 'Swadeshi',
    category: 'staples-essentials',
    price: 25,
    mrp: 30,
    unit: '200g',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/soya-chunks.jpeg',
    description: 'Highly nutritious soya bean chunks. Extremely high in protein, absorbing water and juices beautifully in your curries.',
    isVeg: true,
    specialOffer: 'Rate Rs. 25 Only',
    colorTheme: 'amber',
    rating: 4.6,
    reviewsCount: 145,
    inStock: true,
  },
  {
    id: 'premium-cloves',
    name: 'Whole Premium Spice Clove (Laung)',
    brand: 'Bazar Spices',
    category: 'staples-essentials',
    price: 30,
    mrp: 40,
    unit: '50g',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/premium-cloves.jpeg',
    description: 'Hand-picked dried clove buds. Deep dark brown color with high essential oils that provide a powerful aroma.',
    isVeg: true,
    specialOffer: 'MRP Rs. 30 Offer',
    colorTheme: 'stone',
    rating: 4.7,
    reviewsCount: 78,
    inStock: true,
  },
  {
    id: 'toor-dal',
    name: 'Swadeshi Arhar Toor Dal (Unpolished)',
    brand: 'Swadeshi',
    category: 'staples-essentials',
    price: 155,
    mrp: 175,
    unit: '1 Kg',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/arahar.jpeg',
    description: 'Premium quality yellow split pigeon peas (Arhar dal). Unpolished to retain natural nutrients, fibers, and delicious taste.',
    isVeg: true,
    specialOffer: '0% GST - Loose Price',
    colorTheme: 'amber',
    rating: 4.8,
    reviewsCount: 420,
    inStock: true,
  },
  {
    id: 'moong-dal',
    name: 'Premium Yellow Split Moong Dal',
    brand: 'Swadeshi',
    category: 'staples-essentials',
    price: 115,
    mrp: 130,
    unit: '1 Kg',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/moong.jpeg',
    description: 'Light on digestion, high-protein split yellow moong. Perfectly clean seeds with no artificial coloring.',
    isVeg: true,
    specialOffer: 'Easy to Digest',
    colorTheme: 'emerald',
    rating: 4.7,
    reviewsCount: 215,
    inStock: true,
  },
  {
    id: 'chana-dal',
    name: 'Swadeshi Cleaned Chana Dal Premium',
    brand: 'Swadeshi',
    category: 'staples-essentials',
    price: 85,
    mrp: 100,
    unit: '1 Kg',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/chana-dal.jpeg',
    description: 'Bold-sized split Bengal gram. Sourced from organic farms, rich in plant-based proteins, perfect for making dal tadka.',
    isVeg: true,
    specialOffer: 'Packaged Ki Quality',
    colorTheme: 'yellow',
    rating: 4.8,
    reviewsCount: 310,
    inStock: true,
  },

  // --- OILS & GHEE ---
  {
    id: 'fortune-mustard-pouch',
    name: 'Fortune Premium Kachi Ghani Pure Mustard Oil (1L Bottle)',
    brand: 'Fortune',
    category: 'oils-ghee',
    price: 175,
    mrp: 195,
    unit: '1 Litre',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/fortune-mustard-bottle.jpeg',
    description: 'Traditional cold-pressed mustard oil in a high-quality PET bottle. Rich in aroma, strong pungency, and authentic taste for delicious cooking.',
    isVeg: true,
    specialOffer: '100% Pure Bottle',
    colorTheme: 'amber',
    rating: 4.8,
    reviewsCount: 560,
    inStock: true,
  },
  {
    id: 'saloni-mustard-oil',
    name: 'Saloni Kachchi Ghani Mustard Oil',
    brand: 'Saloni',
    category: 'oils-ghee',
    price: 170,
    mrp: 190,
    unit: '1 Litre',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/saloni-mustard-oil.jpeg',
    description: 'Agmark Mustard Oil Grade-I. Extracted using traditional wooden expeller methods, keeping natural nutrients completely intact.',
    isVeg: true,
    specialOffer: 'Agmark Grade 1',
    colorTheme: 'amber',
    rating: 4.7,
    reviewsCount: 380,
    inStock: true,
  },
  {
    id: 'kings-soyabean-oil',
    name: 'King\'s Refined Soyabean Oil',
    brand: 'King\'s',
    category: 'oils-ghee',
    price: 135,
    mrp: 155,
    unit: '1 Litre',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/kings-soyabean-oil.jpeg',
    description: 'Healthy and light refined soyabean oil. Contains rich Omega-3, Omega-6, and plant sterols for absolute cardiac wellness.',
    isVeg: true,
    specialOffer: 'Goodness of Health',
    colorTheme: 'lime',
    rating: 4.5,
    reviewsCount: 230,
    inStock: true,
  },
  {
    id: 'fortune-mustard-bottle',
    name: 'Fortune Premium Kachi Ghani Pure Mustard Oil (5L Can)',
    brand: 'Fortune',
    category: 'oils-ghee',
    price: 820,
    mrp: 890,
    unit: '5 Litre',
    description: 'Family pack jerry can of premium, cold-pressed mustard oil. Ideal for monthly stock, preserving freshness and pungency.',
    isVeg: true,
    specialOffer: 'Mega Pack Savings',
    colorTheme: 'amber',
    rating: 4.9,
    reviewsCount: 412,
    inStock: true,
  },
  {
    id: 'bail-kolhu-oil',
    name: 'Bail Kolhu Kachchi Ghani Mustard Oil',
    brand: 'Bail Kolhu',
    category: 'oils-ghee',
    price: 178,
    mrp: 198,
    unit: '1 Litre',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/bail-kolhu-oil.jpeg',
    description: 'Iconic mustard oil prepared using wooden press kolhu filters. Famous for its authentic flavor and eye-watering strong pungency.',
    isVeg: true,
    specialOffer: 'Traditional Taste',
    colorTheme: 'red',
    rating: 4.9,
    reviewsCount: 680,
    inStock: true,
  },
  {
    id: 'raag-palmolein',
    name: 'Raag Gold Refined Palmolein Oil',
    brand: 'Raag',
    category: 'oils-ghee',
    price: 110,
    mrp: 130,
    unit: '1 Litre',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/raag-palmolein.jpeg',
    description: 'Vitamin-fortified refined palmolein oil. High smoke point makes it highly suitable for deep-frying puris, pakoras, and papads.',
    isVeg: true,
    specialOffer: 'MUFA Rich - Light',
    colorTheme: 'yellow',
    rating: 4.3,
    reviewsCount: 140,
    inStock: true,
  },
  {
    id: 'fortune-groundnut',
    name: 'Fortune Gold Nut Refined Groundnut Oil',
    brand: 'Fortune',
    category: 'oils-ghee',
    price: 190,
    mrp: 215,
    unit: '1 Litre',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/fortune-groundnut.jpeg',
    description: 'Refined peanut/groundnut oil. Brings a subtle nutty aroma and flavor to your stir-fries and roasted curries.',
    isVeg: true,
    specialOffer: 'Gold Nut Quality',
    colorTheme: 'orange',
    rating: 4.6,
    reviewsCount: 204,
    inStock: true,
  },
  {
    id: 'ananda-ghee',
    name: 'Ananda Desi Ghee Agmark Special Grade',
    brand: 'Ananda',
    category: 'oils-ghee',
    price: 340,
    mrp: 380,
    unit: '500ml',
    image: 'https://kkfemwduwimomkalgzua.supabase.co/storage/v1/object/public/store/ananda-ghee.jpeg',
    description: 'Since 1989. Rich golden granulated desi cow ghee. Brimming with high vitamins and essential fatty acids.',
    isVeg: true,
    specialOffer: 'Agmark Special Grade',
    colorTheme: 'amber',
    rating: 4.8,
    reviewsCount: 310,
    inStock: true,
  },
  {
    id: 'namaste-india-ghee',
    name: 'Namaste India Pure Desi Ghee',
    brand: 'Namaste India',
    category: 'oils-ghee',
    price: 335,
    mrp: 375,
    unit: '500ml',
    description: 'Pure dairy cow ghee with rich granular structure (danedar). Extracted from fresh cow curd, traditional aroma.',
    isVeg: true,
    specialOffer: 'Pure Danedar',
    colorTheme: 'red',
    rating: 4.7,
    reviewsCount: 195,
    inStock: true,
  },

  // --- HOUSEHOLD & CLEANING ---
  {
    id: 'dive-detergent',
    name: 'Dive+ Active Detergent Powder',
    brand: 'Dive+',
    category: 'household-care',
    price: 50,
    mrp: 60,
    unit: '1 Kg',
    description: 'High-impact active oxygen formula. Removes ~100% of tough stains like grease, oil, and mud from collars in 1 wash.',
    isVeg: true,
    specialOffer: 'MRP Rs. 50 Special Offer',
    colorTheme: 'blue',
    rating: 4.5,
    reviewsCount: 215,
    inStock: true,
  },
  {
    id: 'vanya-super-wash',
    name: 'Vanya Care Super Wash Detergent Powder',
    brand: 'Vanya Care',
    category: 'household-care',
    price: 45,
    mrp: 55,
    unit: '1 Kg',
    description: 'With advanced formula. Keeps white clothes absolutely sparkling white and colorful clothes completely bright. Rose & Jasmine scent.',
    isVeg: true,
    specialOffer: 'Rose & Jasmine Fragrance',
    colorTheme: 'cyan',
    rating: 4.3,
    reviewsCount: 110,
    inStock: true,
  },
  {
    id: 'wheel-2in1',
    name: 'Active Wheel 2 in 1 Detergent Powder',
    brand: 'Wheel',
    category: 'household-care',
    price: 65,
    mrp: 72,
    unit: '1 Kg',
    description: 'Brimming with lemon extracts and night-blooming jasmine (Champa) freshness. Gently removes dirt without harming hands.',
    isVeg: true,
    specialOffer: 'Active 2 in 1 Freshness',
    colorTheme: 'emerald',
    rating: 4.6,
    reviewsCount: 520,
    inStock: true,
  },
  {
    id: 'surf-excel-easywash',
    name: 'Surf Excel Easy Wash Detergent Powder',
    brand: 'Surf Excel',
    category: 'household-care',
    price: 135,
    mrp: 150,
    unit: '1 Kg',
    description: 'Premium stain-removing powder that dissolves immediately in bucket water. Super easy scrub-free dirt release.',
    isVeg: true,
    specialOffer: 'Removes 100% Tough Stains',
    colorTheme: 'blue',
    rating: 4.9,
    reviewsCount: 890,
    inStock: true,
  },
  {
    id: 'surf-excel-sachet',
    name: 'Surf Excel Easy Wash Sachet Pack',
    brand: 'Surf Excel',
    category: 'household-care',
    price: 10,
    mrp: 12,
    unit: '80g',
    description: 'Convenient single-use travel sachet of premium Surf Excel Easy Wash powder.',
    isVeg: true,
    specialOffer: 'Easy Travel Sachet',
    colorTheme: 'sky',
    rating: 4.7,
    reviewsCount: 340,
    inStock: true,
  },
  {
    id: 'rin-powder',
    name: 'Rin Bright Like New Detergent Powder',
    brand: 'Rin',
    category: 'household-care',
    price: 82,
    mrp: 90,
    unit: '1 Kg',
    description: 'Formulated with advanced yellow stain brightener molecules that give clothes a lightning bright "look like new" shine.',
    isVeg: true,
    specialOffer: 'Bright Like New',
    colorTheme: 'blue',
    rating: 4.7,
    reviewsCount: 430,
    inStock: true,
  },
  {
    id: 'nirma-advance',
    name: 'Nirma Advance Premium Detergent Powder',
    brand: 'Nirma',
    category: 'household-care',
    price: 68,
    mrp: 75,
    unit: '1 Kg',
    description: 'High active formulation that generates rich foam and works beautifully in both semi-automatic washing machines and manual washes.',
    isVeg: true,
    specialOffer: 'Premium Rose Fragrance',
    colorTheme: 'sky',
    rating: 4.5,
    reviewsCount: 218,
    inStock: true,
  },
  {
    id: 'rin-bar',
    name: 'Rin Big Bar Laundry Detergent Soap',
    brand: 'Rin',
    category: 'household-care',
    price: 20,
    mrp: 22,
    unit: '250g',
    description: 'Rin Bar removes tough dirt from cuffs, collars, and underarms with minimal effort. Leaves an elegant blue brightener look.',
    isVeg: true,
    specialOffer: 'Big Bar Long Lasting',
    colorTheme: 'blue',
    rating: 4.8,
    reviewsCount: 390,
    inStock: true,
  },
  {
    id: 'ghadi-cake',
    name: 'Ghadi Detergent Soap Bar',
    brand: 'Ghadi',
    category: 'household-care',
    price: 15,
    mrp: 18,
    unit: '200g',
    description: 'Pehle Istemaal Karein, Phir Vishwaas Karein! Highly effective soap bar famous across India for mud and grease stain treatment.',
    isVeg: true,
    specialOffer: 'Collar Specialist',
    colorTheme: 'yellow',
    rating: 4.7,
    reviewsCount: 612,
    inStock: true,
  },
  {
    id: 'patanjali-herbal-soap',
    name: 'Patanjali Herbal Wash Detergent Cake',
    brand: 'Patanjali',
    category: 'household-care',
    price: 20,
    mrp: 22,
    unit: '250g',
    description: 'Prepared using pure neem and lemon extracts. Safe and non-allergic formula for hands while removing dirt and germs from fabrics.',
    isVeg: true,
    specialOffer: 'With Neem & Lemon',
    colorTheme: 'green',
    rating: 4.6,
    reviewsCount: 167,
    inStock: true,
  },
  {
    id: 'surf-excel-bar',
    name: 'Surf Excel Stain Eraser Soap',
    brand: 'Surf Excel',
    category: 'household-care',
    price: 10,
    mrp: 10,
    unit: '100g',
    description: 'Power of Surf Excel powder condensed in a handy soap block. Rub directly over stubborn food stains to erase them.',
    isVeg: true,
    specialOffer: 'Stain Eraser Rs. 10',
    colorTheme: 'orange',
    rating: 4.8,
    reviewsCount: 450,
    inStock: true,
  },
  {
    id: 'anchor-toothbrush',
    name: 'Anchor Power Flexi Medium Toothbrush',
    brand: 'Anchor',
    category: 'household-care',
    price: 18,
    mrp: 20,
    unit: '1 Unit',
    description: 'Flexible neck toothbrush with premium zignog bristle technology. Effectively sweeps plaque from between teeth gums.',
    isVeg: true,
    specialOffer: 'Offer Price Rs. 18 Only',
    colorTheme: 'red',
    rating: 4.4,
    reviewsCount: 115,
    inStock: true,
  },
];

export const recipes: Recipe[] = [
  {
    id: 'recipe-masala-maggi',
    name: 'Ultimate Indian Street Masala Maggi',
    description: 'A street-style elevated version of your favourite noodles cooked with premium cloves, vegetables, and ghee.',
    prepTime: '10 mins',
    difficulty: 'Easy',
    imagePlaceholder: '🍜',
    ingredients: [
      { productId: 'maggi-noodles', quantityRequired: 2, customNote: 'Core spicy noodles base' },
      { productId: 'namaste-india-ghee', quantityRequired: 1, customNote: 'For cooking veggies in golden ghee' },
      { productId: 'premium-cloves', quantityRequired: 1, customNote: 'Crack 2 cloves in hot ghee for signature aroma' },
      { productId: 'tata-salt', quantityRequired: 1, customNote: 'A tiny pinch to season your chopped veggies' },
    ],
    steps: [
      'Finely chop onions, tomatoes, and green chillies.',
      'Heat 1 tablespoon of Namaste India Desi Ghee in a pan.',
      'Add 2 buds of Whole Premium Clove (Laung) and let them crackle to release their aromatic oils.',
      'Sauté the chopped onions and chillies until golden brown, then stir in tomatoes.',
      'Add 2 cups of water, a tiny pinch of Tata Salt, and bring it to a rolling boil.',
      'Break Maggi noodle blocks into halves, add to boiling water along with both tastemaker sachets.',
      'Cook on medium heat for exactly 2-3 minutes until water is absorbed. Serve hot and steaming!'
    ]
  },
  {
    id: 'recipe-tadka-chana-dal',
    name: 'Dhaba-Style Aromatic Chana Dal Tadka',
    description: 'A protein-rich rich yellow split chickpea curry tempered in hot Fortune mustard oil with spices and ghee.',
    prepTime: '35 mins',
    difficulty: 'Medium',
    imagePlaceholder: '🍲',
    ingredients: [
      { productId: 'chana-dal', quantityRequired: 1, customNote: 'High protein unpolished Bengal Gram' },
      { productId: 'fortune-mustard-bottle', quantityRequired: 1, customNote: 'Cold pressed oil for rich traditional tadka' },
      { productId: 'ananda-ghee', quantityRequired: 1, customNote: 'Double temper on top for buttery taste' },
      { productId: 'tata-salt', quantityRequired: 1, customNote: 'For pressure cooking the pulses' },
    ],
    steps: [
      'Wash 1 cup of Swadeshi Chana Dal thoroughly and soak in warm water for 20 minutes.',
      'In a pressure cooker, add soaked dal, 3 cups of water, 1 teaspoon of Tata Salt, and cook for 4-5 whistles until tender.',
      'In a frying pan, heat 2 tablespoons of Fortune Mustard Oil until it smokes slightly.',
      'Sauté garlic, ginger, chopped onions, and cumin seeds until browned.',
      'Stir in tomato purée, red chilli powder, and turmeric. Cook until oil separates.',
      'Pour cooked Chana Dal into the pan and simmer on low heat for 5 minutes.',
      'Prepare second tempering: Heat 1 tablespoon of Ananda Ghee in a small ladle, add a pinch of asafoetida (hing) and dry red chillies, and pour directly over the dal. Garnish with coriander!'
    ]
  },
  {
    id: 'recipe-fasting-platter',
    name: 'Crispy Vrat Special Fasting Platter',
    description: 'A light, fasting-friendly combo of crispy Sabudana papad and Potato papad sprinkled with Catch black salt.',
    prepTime: '15 mins',
    difficulty: 'Easy',
    imagePlaceholder: '🍘',
    ingredients: [
      { productId: 'mothers-sabudana-papad', quantityRequired: 1, customNote: 'Tapioca pearls papad with sendha namak' },
      { productId: 'mothers-potato-papad', quantityRequired: 1, customNote: 'Sun-dried aloo papad' },
      { productId: 'kings-soyabean-oil', quantityRequired: 1, customNote: 'Light soyabean oil for clean deep frying' },
      { productId: 'catch-black-salt', quantityRequired: 1, customNote: 'Sprinkle kala namak for ultimate tanginess' },
    ],
    steps: [
      'In a deep kadhai/frying pan, heat 2 cups of King\'s Refined Soyabean Oil on high heat (high smoke point makes it perfect).',
      'Lower heat slightly to medium. Carefully slide in Mother\'s Recipe Sabudana Papad.',
      'Press down gently with a slotted spatula. Watch it puff up into snowy white crispy pearls within 5 seconds!',
      'Drain on a paper towel. Next, deep fry Mother\'s Recipe Potato Papad for 3-4 seconds until golden crispy.',
      'Sprinkle Catch Sprinkler Black Salt immediately over hot fried papads for a tangy, mouthwatering kick.',
      'Serve as a perfect snack during fasts or with hot ginger chai.'
    ]
  }
];
